# roles/common/tasks/main.yml

- name: Update apt cache and install prerequisite packages
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker, Docker Compose, and related packages
  become: yes
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
    update_cache: yes

- name: Add user to the docker group to run docker without sudo
  become: yes
  user:
    name: "{{ ansible_user }}" # inventory에 정의된 사용자(ubuntu)를 docker 그룹에 추가
    groups: docker
    append: yes

- name: Ensure Docker service is started and enabled
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes