- name: Ensure project directory exists
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Copy Kurtosis and Docker Compose configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ project_dir }}/{{ item }}"
    mode: '0644'
  with_items:
    - kurtosis.yml